# This is the configuration used to check the rubocop source code.

Rails:
  Enabled: true

AllCops:
  Exclude:
    - spec/support/spec_helper.rb
    - spec/rails_helper.rb
    - db/**/*
    - docs/**/*
    - config/**/*
    - bin/**/*

Metrics/ClassLength:
  Exclude:
    - app/models/auction.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - app/admin/**/*
    - app/dealer/**/*
    - lib/tasks/pipedrive.rake

Documentation:
  Enabled: false

LineLength:
  Max: 99

HasAndBelongsToMany:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MultilineTernaryOperator:
  Exclude:
    - app/admin/**/*