
development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailgun_password: <%= ENV["MAILGUN_PASSWORD"] %>
  mailgun_domain: <%= ENV["MAILGUN_DOMAIN"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailgun_password: <%= ENV["MAILGUN_PASSWORD"] %>
  mailgun_domain: <%= ENV["MAILGUN_DOMAIN"] %>
